Enable the ShellCheck check prefer-double-quotes
This was done because of a personal preference to use double-quoted
strings over single-quoted strings and always forgetting what characters
Bash has a special interpretation of. This check is implemented in my
fork of ShellCheck, and currently I do not intend to try merging this
upstream. Hence, my decision to also maintain a fork of its pre-commit
Git repository as well.

diff --git a/create-repo b/create-repo
--- a/create-repo
+++ b/create-repo
@@ -9,7 +9,7 @@ PROGNAME="$(basename "$0")"
 readonly PROGNAME
 
 if ! [ "$(command -v aptly)" ]; then
-    printf '%s: %s\n' "${PROGNAME}" "aptly cannot be found in the PATH!" >&2
+    printf "%s: %s\n" "${PROGNAME}" "aptly cannot be found in the PATH!" >&2
     exit 1
 fi
 
